### ISSUE TITLE
Does not run on Docker on windows

### ISSUE THREAD

**Issue by MrDj200** [shiaky/breitbandmessung#10]
When I try to run it on my Docker installation on windows it errors out with this:

```
PREPARING SPEEDTEST
could not click element
Error: TimeoutError: waiting for selector "#root > div > div.fade.modal-md.modal.show > div > div > div.justify-content-between.modal-footer > button:nth-child(2)" failed: timeout 30000ms exceeded
```

I adapted the start command to `docker run -v ./messprotokolle:/export/ shiaky/breitbandmessung:latest` since without changing it, it errord in this: 
```
docker: Error response from daemon: create $PWD/messprotokolle: "$PWD/messprotokolle" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
```

Or did I just mess up the start command?

**Comment by shiaky** [comment]
Hi MrDj200,
i fixed the issue. You can find a new image by running 

~~~
docker pull shiaky/breitbandmessung:latest
~~~

Then you can run it as documented in the README.md.

AFAIK `docker run -v ./messprotokolle:/export/ shiaky/breitbandmessung:latest` will never work since Docker CLI does not allow defining relative paths. Instead, use PWD or use the absolute path.
