### ISSUE TITLE
The config files are not integrated (with Unraid 6.12.6)

### ISSUE THREAD

**Issue by SPN34** [shiaky/breitbandmessung#13]
Hi :-)
Unfortunately it doesn't work as described in the instructions

"...Create a config folder and a config.cfg file...."
done with run every 2 hours (not like in the example with 2 minutes (see crontab=0 */2 * * *))

![grafik](https://github.com/shiaky/breitbandmessung/assets/157501367/79466263-6d6d-489c-82ad-c2852afcc9e9)

but this config file will not executed // the measurement runs every 2 minutes :-(

Any ​suggestions for a solution.
THX
Sebastian

**Comment by doubleugm** [comment]
Hi Sebastian,
i have createt the config.cfg in the container /usr/src/app/config # nano config.cfg 
![grafik](https://github.com/shiaky/breitbandmessung/assets/122892259/0189a03b-a9e1-45ea-96f2-a578526b587d)
If the file (still empty) is present in Unraid, then the volume is mapped correctly
Then i wrote the data via Unraid.
Container restart.

Yes the container restarts every time  because run_once=true  =   The measurement will run one time and the Container will be terminated  -> But Unraid will restart the Container if he stop ... and so on
The Way is -> set to run_once=false = automatic with cron -->  [https://github.com/Shnezzin/breitbandmessung/issues/1](url)

timezone=Europe/Berlin
crontab=0 * * * *
run_once=false    
run_on_startup=true
/usr/src/app/config # 

Grüße
;) 


Info:
![grafik](https://github.com/shiaky/breitbandmessung/assets/122892259/1b5802f2-0486-4f15-877d-8bdaa44af82b)

**Comment by shiaky** [comment]
This is not related to this repo I assume.
