### ISSUE TITLE
Incompatibility with 3.0.0?

### ISSUE THREAD

**Issue by TobiasPf** [shiaky/breitbandmessung#2]
Could it be that this docker isn't comaptibal with the current version of the Breitbandmessung anymore?
Regards
Tobias

**Comment by shiaky** [comment]
Hi Tobias,
you are right. Sorry for the late response. I updated the code and the docker image. Please feel free to test it and let me know if there are any further problems. I'm closing the issue for now. Please feel free to open it again if you encounter any new problems.

Thank you for participating :) 

Merry Christmas,
Robin

**Comment by TobiasPf** [comment]
Wow! Thanks alot!
I think it's a great project and thank you for realising this.
Is there a way for me to show my appreciation?
Do you have Paypal?
Regards
Tobias
Mit freundlichen Grüßen
Tobias Pfeifer

24.12.2021 10:38:33 shiaky ***@***.***>:

**Comment by shiaky** [comment]
Hi Tobias,
no it is a pleasure for me that someone is using it. I was creating it for myself because I was so upset that I have to do such a measurement campaign without having the possibility to automate the measurements in any way. I'm glad that this projects also helps other people to get the contractually guaranteed speed from their internet service providers. 

Cheers,
Robin
