### ISSUE TITLE
Settings to run on Synology NAS

### ISSUE THREAD

**Issue by Numior** [shiaky/breitbandmessung#5]
Hi all, does anyone have this running on a Synology NAS?  
The container runs, but my the results are unfortunately not written out in the desired destination folder. I used the following mountpath.

![image](https://user-images.githubusercontent.com/7684740/154041124-935e327e-cab0-49c8-864b-c642dfd9edf6.png)

Other settings not changed...

**Comment by shiaky** [comment]
Hi @Numior, if it really runs at yours it could be that the docker container is missing write permissions in the export folder. But as I have seen just now is that the latest docker image seems to be not working since there seems to be some change on the breitbandmessung website. Give me some hours to fix this and publish a new image. Meanwhile, you can try it with an ssh connection on your Synology:

~~~
cd /tmp
mkdir messprotokolle
docker run -v $PWD/messprotokolle:/export/ shiaky/breitbandmessung:latest
~~~

If you get an error there it's likely that you have to wait till I adapted the container to the most recent version.

Cheers

**Comment by shiaky** [comment]
Hello @Numior, 
the problems seem to have been on breitbandmessung's side. But now the website works again as before and so does the old docker-image of breitbandmessung. Please try it again on your Synology. If it still doesn't work, please try the manual steps I posted above. If they do not work either, please contact me again.

I would close the ticket for now. Please feel free to open it again if you can not manage to get it running.
Cheers
