### ISSUE TITLE
continuously uses CPU resources

### ISSUE THREAD

**Issue by furrnace** [shiaky/breitbandmessung#6]
as far as I understood the concept of this container, it uses firefox in a cron job to execute the breitbandmessung test. 
the container uses CPU resources all the time, not only when the cron job runs. 
what is the reason?

I tried the breitbandmessung-node container, but it does not export to influxdb. I do need the export to influxdb.

**Comment by shiaky** [comment]
Hi @furrnace,
I'm afraid I do not really get your point ;) Neither the container is using Firefox nor any cronjob is running. The container is meant to perform one single "breitbandmessung" and save the results to a csv file. When the "breitbandmessung" is running the container will have some CPU usage of course. But since the container will exit after one successful or failed attempt of measurement there should be no continued cpu usage since it is not running anymore ;) 

If you like, you can create a cronjob that is running the container continuously and you can write a wrapper that is filling the data from the csv file to influxdb.

So please help me to understand how I can help you here.
